aurora/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
    path('', include('information.urls')),
    path('dashboard/', include('dashboard.urls')),

    path("password_reset/", auth_views.PasswordResetView.as_view(),
         name="password_reset"),
    path("password_reset_done/", auth_views.PasswordResetDoneView.as_view(),
         name="password_reset_done"),
    path("password_reset_confirm/<uidb64>/<token>", auth_views.PasswordResetConfirmView.as_view(),
         name="password_reset_confirm"),
    path("password_reset_complete/",
         auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/urls.py
# Imports

from django.urls import path
from . import views

# URL Configurations

app_name = "authentication"
urlpatterns = [
    path("sign_in/", views.sign_in, name="sign_in"),
    path("sign_up/", views.sign_up, name="sign_up"),
    path("sign_out/", views.sign_out, name="sign_out"),

    path("password_reset/", views.password_reset, name="password_reset"),
    path("password_change/<uidb64>/<token>/",
         views.password_change, name="password_change"),

    path("verify_user/<huid>/", views.verify_user, name="verify_user")
]

main/urls.py
# Imports

from django.urls import path
from . import views

# URL Configurations

app_name = "main"
urlpatterns = [
    path("", views.index, name="index"),
    path("products/", views.products, name="products"),
    path("product/<int:id>", views.product, name="product"),
    path("category/<int:id>", views.category, name="category"),
    path("brand/", views.brand, name="brand"),
    path("sub_category/<int:id>", views.sub_category, name="sub_category"),
    path("product_type/<int:id>", views.product_type, name="product_type"),
    path("seller/", views.seller, name="seller"),
]

authentication/views.py
# Imports


from dashboard.views import watchlist
from authentication.models import CustomUser
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.tokens import PasswordResetTokenGenerator

from django.shortcuts import redirect, render, reverse
from django.core.mail import send_mail
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.http.response import HttpResponsePermanentRedirect

from dashboard.models import *

import hashlib


# Views
def sign_in(request):

    status = 200
    if request.user.is_anonymous:
        if request.method == "POST":
            username = request.POST["username"]
            password = request.POST["password"]

            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect(reverse("dashboard:home"))
            else:
                if User.objects.filter(username=username).count() == 0:
                    messages.add_message(
                        request, messages.ERROR, "Username does not belong to any account.")
                    status = 401
                else:
                    messages.add_message(
                        request, messages.ERROR, "Password is incorrect.")
                    status = 401

        context = {}
        return render(request, "authentication/sign_in.html", context, status=status)

    else:
        return HttpResponsePermanentRedirect(reverse("dashboard:home"))


def sign_up(request):

    status = 200

    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        password = request.POST["password"]

        if User.objects.filter(username=username).count() != 0:
            messages.add_message(
                request, messages.ERROR, "This username has been taken by another account.")
            status = 409
        elif User.objects.filter(email=email).count() != 0:
            messages.add_message(
                request, messages.ERROR, "An account has already been opened using this email.")
            status = 409
        elif len(password) < 8:
            messages.add_message(
                request, messages.ERROR, "Password must be atleast 8 characters in length.")
            status = 406
        else:
            user = User.objects.create_user(
                username=username, email=email, password=password)
            user.save()

            custom_user = CustomUser.objects.create(
                user=user, huid=hashlib.md5(str(user.id).encode()).hexdigest(), is_verified=False)
            custom_user.save()

            cart = Cart.objects.create(user=custom_user)
            cart.save()

            watchlist = Watchlist.objects.create(user=custom_user)
            watchlist.save()

            wishlist = Wishlist.objects.create(user=custom_user)
            wishlist.save()

            send_mail(
                subject="Verify Account",
                message=f"{custom_user.huid}",
                from_email="yasazaheen728@gmail.com",
                recipient_list=[user.email],
                fail_silently=False,
                html_message=f"<a href='http://127.0.0.1:8000/auth/verify_user/{custom_user.huid}/' >Click here</a>"
            )

            login(request, user)
            return redirect(reverse("dashboard:home"))

    return render(request, "authentication/sign_up.html", status=status)


def sign_out(request):

    if request.user.is_anonymous:
        return HttpResponsePermanentRedirect(reverse("authentication:sign_in"))
    else:
        logout(request)
        return HttpResponsePermanentRedirect(reverse("authentication:sign_in"))


def password_reset(request):

    status = 200

    if request.method == "POST":
        email = request.POST["email"]

        if User.objects.filter(email=email).count() == 0:
            messages.add_message(
                request, messages.ERROR, "Email does not belong to any account.")
            status = 404
        else:
            user = User.objects.get(email=email)
            uidb64 = urlsafe_base64_encode((user.id).to_bytes(2, "big"))
            token = PasswordResetTokenGenerator().make_token(user)

            send_mail(
                subject="Password Reset Confirmation",
                message=f"{uidb64}/{token}",
                from_email="yasazaheen728@gmail.com",
                recipient_list=[email],
                fail_silently=False,
                html_message=f"<a href='http://127.0.0.1:8000/auth/password_change/{uidb64}/{token}/' >Click here</a>"
            )

            messages.add_message(
                request, messages.SUCCESS, 'Email has been sent. Please check your inbox.')

    context = {}
    return render(request, "authentication/password_reset.html", context, status=status)


def password_change(request, uidb64, token):

    status = 200

    user = User.objects.get(id=int.from_bytes(
        urlsafe_base64_decode(uidb64), "big"))

    if PasswordResetTokenGenerator().check_token(user, token) == True:
        if request.method == "POST":
            password = request.POST["password"]

            if len(password) < 8:
                messages.add_message(
                    request, messages.ERROR, "Password must be atleast 8 characters in length.")
                status = 406
            else:
                user.set_password(password)
                user.save()
                messages.add_message(
                    request, messages.SUCCESS, 'Passwords reset successfully!')
                return redirect(reverse("authentication:sign_in"))
    else:
        return redirect(reverse("main:index"))

    context = {}
    return render(request, "authentication/password_change.html", context, status=status)


def verify_user(request, huid):

    custom_user = CustomUser.objects.get(huid=huid)

    if custom_user.is_verified:
        context = {
            "message": "Your account has already been verified!"
        }
        return render(request, "authentication/verify_user.html", context, status=200)
    else:
        custom_user.is_verified = True
        custom_user.save()
        context = {
            "message": "Your account has been verified!"
        }
        return render(request, "authentication/verify_user.html", context, status=400)

authentication/templates/authentication/password_change.html
{% extends "templates/base.html" %} {% load static %}
<hr />
{% block content %}
<link
  rel="stylesheet"
  href="{% static 'authentication/css/password_change.css' %}"
/>

<div class="password-change">
  <div class="password-change__img">
    <img src="{% static 'authentication/img/password_change.svg' %}" alt="" />
    <div class="frost bg-red" style="height: 50vh; width: 50vh"></div>
  </div>
  <div class="password-change__form">
    {% if messages %} {% for message in messages %}
    <p class="s-l w-h {{ message.tags }}">{{ message }}</p>
    {% endfor %} {% endif %}

    <p class="s-2l w-h">Reset Password</p>

    <form method="POST">
      {% csrf_token %}
      <div style="margin: 25px 0px">
        <!-- Enter New Password -->
        {% with title="Enter new password" %}
        <span></span>
        {% with type="password" %}
        <span></span>
        {% with icon="password" %}
        <span></span>
        {% with name="password" %}
        <span></span>
        {% include "templates/textInput.html" %}
        <span></span>
        {% endwith %}
        <span></span>
        {% endwith %}
        <span></span>
        {% endwith %}
        <span></span>
        {% endwith %}
      </div>

      <button class="bg-red c-white stretch padding">Change Password</button>
    </form>
  </div>
</div>
{% endblock content %}

authentication/templates/authentication/password_reset.html
{% extends "templates/base.html" %} {% load static %}
<hr />
{% block content %}
<link
  rel="stylesheet"
  href="{% static 'authentication/css/password_reset.css' %}"
/>

<div class="password-reset">
  <div class="password-reset__img">
    <img src="{% static 'authentication/img/password_reset.svg' %}" alt="" />
    <div class="frost bg-mediumBlue" style="height: 50vh; width: 50vh"></div>
  </div>
  <div class="password-reset__form">
    {% if messages %} {% for message in messages %}
    <p class="s-l w-h {{ message.tags }}">{{ message }}</p>
    {% endfor %} {% endif %}

    <p class="s-2l w-h">Forgot Password?</p>

    <form method="POST">
      {% csrf_token %}
      <div style="margin: 25px 0px">
        {% with title="Enter your email here" %}
        <span></span>
        {% with type="email" %}
        <span></span>
        {% with icon="email" %}
        <span></span>
        {% with name="email" %}
        <span></span>
        {% with required="True" %}
        <span></span>
        {% include "templates/textInput.html" %}
        <span></span>
        {% endwith %}
        <span></span>
        {% endwith %}
        <span></span>
        {% endwith %}
        <span></span>
        {% endwith %}
        <span></span>
        {% endwith %}
      </div>

      <button class="bg-mediumBlue c-white stretch padding">
        Send reset link
      </button>
    </form>
  </div>
</div>
{% endblock content %}

authentication/templates/authentication/reset_password_confirm.html
{% extends "templates/base.html" %} {% load static %}
<hr />
{% block content %}
<link
  rel="stylesheet"
  href="{% static 'authentication/css/reset_password_confirm.css' %}"
/>

<div class="reset-password-confirm">
  <div class="reset-password-confirm__img">
    <img
      src="{% static 'authentication/img/reset_password_confirm.svg' %}"
      alt=""
    />
    <div class="frost bg-red" style="height: 50vh; width: 50vh"></div>
  </div>
  <div class="reset-password-confirm__form">
    <p class="s-2l w-h">Reset Password</p>

    <div style="margin: 25px 0px">
      <!-- Enter new password -->
      {% with title="Enter new password" %}
      <span></span>
      {% with type="password" %}
      <span></span>
      {% with icon="password" %}
      <span></span>
      {% include "templates/textInput.html" %}
      <span></span>
      {% endwith %}
      <span></span>
      {% endwith %}
      <span></span>
      {% endwith %}
      <!-- Confirm new password -->
      {% with title="Confirm new password" %}
      <span></span>
      {% with type="password" %}
      <span></span>
      {% with icon="check" %}
      <span></span>
      {% include "templates/textInput.html" %}
      <span></span>
      {% endwith %}
      <span></span>
      {% endwith %}
      <span></span>
      {% endwith %}
    </div>

    <button class="bg-red c-white stretch padding">Send reset link</button>
  </div>
</div>
{% endblock content %}

authentication/templates/authentication/sign_in.html
{% extends "templates/base.html" %} {% load static %}
<hr />
{% block content %}
<link rel="stylesheet" href="{% static 'authentication/css/sign_in.css' %}" />
<div class="sign-in">
  <div class="sign-in__img">
    <img src="{% static 'authentication/img/sign_in.svg' %}" alt="" />
    <div class="frost bg-orange" style="height: 50vh; width: 50vh"></div>
  </div>
  <div class="sign-in__form">
    {% if messages %} {% for message in messages %}
    <p class="s-l w-h {{ message.tags }}">{{ message }}</p>
    {% endfor %} {% endif %}

    <p class="s-2l w-h">Welcome back!</p>
    <pre><p class="s-l w-h">Don't have an account? <a href="{% url 'authentication:sign_up' %}" class="c-orange">Sign up!</a></p></pre>

    <form method="POST">
      {% csrf_token %}
      <div style="margin: 25px 0px">
        <!-- Email -->
        {% with type="text" %}
        <span></span>
        {% with title="Username" %}
        <span></span>
        {% with icon="person" %}
        <span></span>
        {% with name="username" %}
        <span></span>
        {% with required="True" %}
        <span></span>
        {% include "templates/textInput.html" %}
        <span></span>
        {% endwith %}
        <span></span>
        {% endwith %}
        <span></span>
        {% endwith %}
        <span></span>
        {% endwith %}
        <span></span>
        {% endwith %}

        <!-- Password -->
        {% with type="password" %}
        <span></span>
        {% with title="Password" %}
        <span></span>
        {% with icon="password" %}
        <span></span>
        {% with name="password" %}
        <span></span>
        {% with required="True" %}
        <span></span>
        {% include "templates/textInput.html" %}
        <span></span>
        {% endwith %}
        <span></span>
        {% endwith %}
        <span></span>
        {% endwith %}
        <span></span>
        {% endwith %}
        <span></span>
        {% endwith %}

        <pre><p class="s-l w-h">Forgot password? <a href="{% url 'authentication:password_reset' %}" class="c-orange">Click here!</a></p></pre>
      </div>

      <button class="bg-orange c-white stretch padding" type="submit">
        Sign in
      </button>
    </form>
  </div>
</div>
{% endblock content %}

authentication/templates/authentication/sign_up.html
{% extends "templates/base.html" %} {% load static %}
<hr />
{% block content %}
<link rel="stylesheet" href="{% static 'authentication/css/sign_up.css' %}" />

<div class="sign-up">
  <div class="sign-up__img">
    <img src="{% static 'authentication/img/sign_up.svg' %}" alt="" />
    <div class="frost bg-darkBlue" style="height: 50vh; width: 50vh"></div>
  </div>
  <div class="sign-up__form">
    {% if messages %} {% for message in messages %}
    <p class="s-l w-h {{ message.tags }}">{{ message }}</p>
    {% endfor %} {% endif %}

    <p class="s-2l w-h">Welcome to Aurora!</p>

    <pre><p class="s-l w-h">Already have an account? <a href="{% url 'authentication:sign_in' %}" class="c-medium-blue">Sign in!</a></p></pre>

    <form method="POST">
      {% csrf_token %}
      <div style="margin: 25px 0px">
        <!-- Username -->
        {% with title="Enter your username here" %}
        <span></span>
        {% with type="text" %}
        <span></span>
        {% with icon="person" %}
        <span></span>
        {% with name="username" %}
        <span></span>
        {% with required="True" %}
        <span></span>
        {% include "templates/textInput.html" %}
        <span></span>
        {% endwith %}
        <span></span>
        {% endwith %}
        <span></span>
        {% endwith %}
        <span></span>
        {% endwith %}
        <span></span>
        {% endwith %}
        <!-- Email -->
        {% with title="Enter your email here" %}
        <span></span>
        {% with type="email" %}
        <span></span>
        {% with icon="email" %}
        <span></span>
        {% with name="email" %}
        <span></span>
        {% with required="True" %}
        <span></span>
        {% include "templates/textInput.html" %}
        <span></span>
        {% endwith %}
        <span></span>
        {% endwith %}
        <span></span>
        {% endwith %}
        <span></span>
        {% endwith %}
        <span></span>
        {% endwith %}
        <!-- Password -->
        {% with title="Enter your password here" %}
        <span></span>
        {% with type="password" %}
        <span></span>
        {% with icon="password" %}
        <span></span>
        {% with name="password" %}
        <span></span>
        {% with required="True" %}
        <span></span>
        {% include "templates/textInput.html" %}
        <span></span>
        {% endwith %}
        <span></span>
        {% endwith %}
        <span></span>
        {% endwith %}
        <span></span>
        {% endwith %}
        <span></span>
        {% endwith %}
      </div>

      <button class="bg-darkBlue c-white stretch padding" type="submit">
        Sign up
      </button>
    </form>
  </div>
</div>

{% endblock content %}

authentication/templates/authentication/verify_user.html
{% extends "templates/base.html" %} {% load static %}
<hr />
{% block content %}
<link
  rel="stylesheet"
  href="{% static 'authentication/css/verify_user.css' %}"
/>

<div class="verify-user">
  <div class="verify-user__img">
    <img src="{% static 'authentication/img/verify_user.svg' %}" alt="" />
    <div class="frost bg-black" style="height: 50vh; width: 50vh"></div>
  </div>
  <div class="verify-user__form">
    <p class="s-2l w-h">{{ message }}</p>
  </div>
</div>
{% endblock content %}