aurora/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
    path('', include('information.urls')),
    path('dashboard/', include('dashboard.urls')),

    path("password_reset/", auth_views.PasswordResetView.as_view(),
         name="password_reset"),
    path("password_reset_done/", auth_views.PasswordResetDoneView.as_view(),
         name="password_reset_done"),
    path("password_reset_confirm/<uidb64>/<token>", auth_views.PasswordResetConfirmView.as_view(),
         name="password_reset_confirm"),
    path("password_reset_complete/",
         auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/urls.py
# Imports

from django.urls import path
from . import views

# URL Configurations

app_name = "authentication"
urlpatterns = [
    path("sign_in/", views.sign_in, name="sign_in"),
    path("sign_up/", views.sign_up, name="sign_up"),
    path("sign_out/", views.sign_out, name="sign_out"),

    path("password_reset/", views.password_reset, name="password_reset"),
    path("password_change/<uidb64>/<token>/",
         views.password_change, name="password_change"),

    path("verify_user/<huid>/", views.verify_user, name="verify_user")
]

dashboard/urls.py
# Imports

from django.urls import path
from . import views

# URL Configurations

app_name = "dashboard"
urlpatterns = [
    path('home/', views.home, name='home'),
    path('cart/', views.cart, name='cart'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('watchlist/', views.watchlist, name="watchlist"),
    path("wishlist/", views.wishlist, name="wishlist"),
    path('crm/', views.crm, name="crm"),
    path('crm/order/<int:id>', views.order, name="order"),
    path("my_products/", views.my_products, name="my_products"),
    path("my_products/edit_product/<int:id>",
         views.edit_product, name="edit_product"),
    path("add_product/", views.add_product, name="add_product"),
    path("add_product/set_category/<int:id>",
         views.set_category, name="set_category"),
    path("add_product/set_sub_category/<int:id>",
         views.set_sub_category, name="set_sub_category"),
    path("add_product/set_product_type/<int:id>",
         views.set_product_type, name="set_product_type"),
    path("add_product/set_filters/<int:id>",
         views.set_filters, name="set_filters"),
    path('revenue/', views.revenue, name="revenue"),
    path('settings/', views.settings, name="settings")
]

main/urls.py
# Imports

from django.urls import path
from . import views

# URL Configurations

app_name = "main"
urlpatterns = [
    path("", views.index, name="index"),
    path("products/", views.products, name="products"),
    path("product/<int:id>", views.product, name="product"),
    path("category/<int:id>", views.category, name="category"),
    path("brand/", views.brand, name="brand"),
    path("sub_category/<int:id>", views.sub_category, name="sub_category"),
    path("product_type/<int:id>", views.product_type, name="product_type"),
    path("seller/", views.seller, name="seller"),
]

dashboard/views.py
# Imports


from datetime import time
from django.contrib import messages
from django.contrib.auth import authenticate
from django.shortcuts import render, redirect, reverse

from authentication.models import *
from dashboard.models import *
from main.models import Category, Filter, ProductType, SubCategory

from main.views import cart_btn_handler, category, product, product_type, sub_category, wishlist_btn_handler, watchlist_btn_handler

# Views


def home(request):

    if request.user.is_authenticated:
        user = CustomUser.objects.get(user=request.user)
        cart = Cart.objects.get(user=user)
        wishlist = Wishlist.objects.get(user=user)
        watchlist = Watchlist.objects.get(user=user)

        context = {
            "user": user,
            "cart": cart,
            "wishlist": wishlist,
            "watchlist": watchlist,
        }

        return render(request, 'dashboard/home.html', context)
    else:
        return redirect(reverse("dashboard:set_sub_category", kwargs={"id": 8}))


def cart(request):

    if request.user.is_authenticated:
        user = CustomUser.objects.get(user=request.user)
        cart = Cart.objects.get(user=user)
        wishlist = Wishlist.objects.get(user=user)
        watchlist = Watchlist.objects.get(user=user)

        context = {
            "user": user,
            "cart": cart,
            "wishlist": wishlist,
            "watchlist": watchlist,

        }

        if request.method == "POST":
            if "cart" in request.POST:
                cart_btn_handler(request, cart)

            if "wishlist" in request.POST:
                wishlist_btn_handler(request, wishlist)

            if "watchlist" in request.POST:
                watchlist_btn_handler(request, watchlist)

            if "submit-cart" in request.POST:
                cart.create_order(request)

        return render(request, "dashboard/cart.html", context)
    else:
        return redirect(reverse("main:index"))


def watchlist(request):

    if request.user.is_authenticated:
        user = CustomUser.objects.get(user=request.user)
        watchlist = Watchlist.objects.get(user=user)
        watchlist.update()

        context = {
            "user": user,
            "watchlist": watchlist,
        }

        return render(request, "dashboard/watchlist.html", context)
    else:
        return redirect(reverse("main:index"))


def wishlist(request):

    if request.user.is_authenticated:
        user = CustomUser.objects.get(user=request.user)
        cart = Cart.objects.get(user=user)
        wishlist = Wishlist.objects.get(user=user)
        watchlist = Watchlist.objects.get(user=user)

        context = {
            "user": user,
            "cart": cart,
            "wishlist": wishlist,
            "watchlist": watchlist,
        }

        if request.method == "POST":
            if "cart" in request.POST:
                cart_btn_handler(request, cart)

            if "wishlist" in request.POST:
                wishlist_btn_handler(request, wishlist)

            if "watchlist" in request.POST:
                watchlist_btn_handler(request, watchlist)

        return render(request, "dashboard/wishlist.html", context)
    else:
        return redirect(reverse("main:index"))


def crm(request):

    if request.user.is_authenticated:
        user = CustomUser.objects.get(user=request.user)

        context = {
            "user": user,
        }

        return render(request, 'dashboard/crm.html', context)

    else:
        return redirect(reverse("main:index"))


def order(request, id):

    if request.user.is_authenticated:
        user = CustomUser.objects.get(user=request.user)
        order = Order.objects.get(id=id)

        total_product_price, total_shipping, total_revenue = order.get_seller_revenue(
            request.user)

        if request.method == "POST":
            order.status = request.POST['order-status']

        order.save()

        context = {
            "user": user,
            "order": order,
            "total_product_price": total_product_price,
            "total_shipping": total_shipping,
            "total_revenue": total_revenue,
        }

        return render(request, 'dashboard/order.html', context)

    else:
        return redirect(reverse("main:index"))


def my_products(request):

    if request.user.is_authenticated:
        user = CustomUser.objects.get(user=request.user)
        products = Product.objects.filter(seller=user)

        context = {
            "products": products
        }

        return render(request, "dashboard/my_products.html", context)

    else:
        return redirect(reverse("main:index"))


def edit_product(request, id):
    if request.user.is_authenticated:
        user = CustomUser.objects.get(user=request.user)
        product = Product.objects.get(id=id)

        if request.method == "POST":
            product.edit_product(request)

        context = {
            "product": product
        }

        return render(request, "dashboard/edit_product.html", context)

    else:
        return redirect(reverse("main:index"))


def add_product(request):

    if request.user.is_authenticated:
        user = CustomUser.objects.get(user=request.user)

        if request.method == "POST":
            product = user.add_product(request)
            return redirect(reverse("dashboard:set_category", kwargs={"id": product.id}))

        context = {}

        return render(request, "dashboard/add_product.html", context)

    else:
        return redirect(reverse("main:index"))


def set_category(request, id):

    if request.user.is_authenticated:

        categories = Category.objects.all()
        product = Product.objects.get(id=id)

        if product.category == None:
            if request.method == "POST":
                category = Category.objects.get(id=request.POST["category"])
                product.category = category
                product.save()
                return redirect(reverse("dashboard:set_sub_category", kwargs={"id": product.id}))

        else:
            return redirect(reverse("dashboard:home"))

        context = {
            "categories": categories
        }

        return render(request, "dashboard/set_category.html", context)

    else:
        return redirect(reverse("main:index"))


def set_sub_category(request, id):

    if request.user.is_authenticated:

        product = Product.objects.get(id=id)
        sub_categories = SubCategory.objects.filter(category=product.category)

        if product.sub_category == None:
            if request.method == "POST":
                sub_category = SubCategory.objects.get(
                    id=request.POST["sub-category"])
                product.sub_category = sub_category
                product.save()
                return redirect(reverse("dashboard:set_product_type", kwargs={"id": product.id}))

        else:
            return redirect(reverse("dashboard:home"))

        context = {
            "sub_categories": sub_categories
        }

        return render(request, "dashboard/set_sub_category.html", context)

    else:
        return redirect(reverse("main:index"))


def set_product_type(request, id):

    if request.user.is_authenticated:

        product = Product.objects.get(id=id)
        product_types = ProductType.objects.filter(
            sub_category=product.sub_category)

        if product.product_type == None:
            if request.method == "POST":
                product_type = ProductType.objects.get(
                    id=request.POST["product-type"])
                product.product_type = product_type
                product.save()
                return redirect(reverse("dashboard:set_filters", kwargs={"id": product.id}))

        else:
            return redirect(reverse("dashboard:home"))

        context = {
            "product_types": product_types
        }

        return render(request, "dashboard/set_product_type.html", context)

    else:
        return redirect(reverse("main:index"))


def set_filters(request, id):

    if request.user.is_authenticated:

        product = Product.objects.get(id=id)
        filters = Filter.objects.filter(
            product_type=product.product_type)
        filter_categories = []

        for filter in filters:
            if filter.filter_category not in filter_categories:
                filter_categories.append(filter.filter_category)

        if request.method == "POST":
            for i in request.POST:
                if i != "csrfmiddlewaretoken":
                    filter = Filter.objects.get(id=request.POST[i])
                    product.filters.add(filter)
                    product.save()
                    return redirect(reverse("main:product"), kwargs={"id": product.id})

        context = {
            "filters": filters,
            "filter_categories": filter_categories
        }

        return render(request, "dashboard/set_filters.html", context)

    else:
        return redirect(reverse("main:index"))


def revenue(request):

    if request.user.is_authenticated:

        user = CustomUser.objects.get(user=request.user)

        todays_revenue, todays_sale, todays_orders = user.get_todays()
        yesterdays_revenue, yesterdays_sale, yesterdays_orders = user.get_yesterdays()
        lastweeks_revenue, lastweeks_sale, lastweeks_orders = user.get_lastweeks()
        last28_revenue, last28_sale, last28_orders = user.get_last28()

        total_revenue, total_sales = user.get_total_revenuesales()

        # DONE: Today

        t_graph_revenue = [0, 0, 0, 0, 0, 0, 0, 0, 0,
                           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        t_graph_sales = [0, 0, 0, 0, 0, 0, 0, 0, 0,
                         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

        for order in todays_orders:
            total_product_price, total_shipping, total_revenue = order.get_seller_revenue(
                request.user)

dashboard/templates/dashboard/crm.html
{% extends "dashboard/dashboard.html" %} {% load static %}
<hr />

{% block viewContent %}

<link rel="stylesheet" href="{% static 'dashboard/css/crm.css' %}" />

<div class="crm">
  {% for order in user.get_seller_orders %}

  <div class="crm__order module shadow">
    <div style="display: flex; justify-content: space-between">
      <p class="s-l w-h" style="margin-bottom: 12.5px">
        Order no. #{{order.id}}
      </p>
      <a href="{% url 'dashboard:order' order.id %}" class="order__link"
        >View Details</a
      >
    </div>
    <!-- TODO: Table -->

    <table class="order__table">
      <tr>
        <td style="width: 50%">
          <p class="s-s w-h">Name</p>
        </td>
        <td style="width: 50%">
          <p class="s-s w-l">{{order.name}}</p>
        </td>
      </tr>
      <tr>
        <td style="width: 50%">
          <p class="s-s w-h">Country</p>
        </td>
        <td style="width: 50%">
          <p class="s-s w-l">{{order.country}}</p>
        </td>
      </tr>
    </table>

    <!-- TODO: Status -->

    <!-- TODO: Products -->

    {% for product in order.products.all %}
    <span></span>
    {% if product.seller == user %}
    <div class="order__product">
      <div class="product-imgs">
        <img src="{{product.image_1.url}}" alt="" />
        <img src="{{product.image_2.url}}" alt="" />
        <img src="{{product.image_3.url}}" alt="" />
        <img src="{{product.image_4.url}}" alt="" />
      </div>
      <div
        style="display: flex; flex-direction: column; justify-content: center"
      >
        <p class="s-m w-h" style="height: fit-content">{{product.name}}</p>
        <pre><p class="s-l w-h">USD {{product.price}}</p><p class="s-s w-l"> + USD {{product.shipping_price}} shipping estimate.</p></pre>
      </div>
    </div>
    {% endif %}
    <span></span>
    {% endfor %}

    <!-- TODO: DOO -->

    <div style="display: flex; justify-content: space-between">
      <p class="s-l w-h">
        Date of order: {{ order.date_of_order|date:"d M Y" }}
      </p>
      <p class="s-l w-h bg-red c-white order__status">{{order.status}}</p>
    </div>
  </div>

  {% endfor %}
</div>

<script src="{% static 'dashboard/js/crm.js' %}"></script>
{% endblock viewContent %}

dashboard/templates/dashboard/dashboard.html
{% load static %}

<link rel="stylesheet" href="{% static 'base/css/base.css' %}" />
<link rel="stylesheet" href="{% static 'dashboard/css/dashboard.css' %}" />
<link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
<div class="main-cont">
  <div class="nav-cont">{% include "dashboard/navbar.html" %}</div>
  <div class="view-cont">
    {% block viewContent %} {% endblock viewContent %}
  </div>
</div>

<script src="{% static 'base/js/base.js' %}"></script>

dashboard/templates/dashboard/my_products.html
{% extends "dashboard/dashboard.html" %} {% load static %}

<hr />
{% block viewContent %}
<link rel="stylesheet" href="{% static 'dashboard/css/my_products.css' %}" />

<div class="my_products">
  {% for product in products %}

  <div class="product">
    <!-- * TODO: Picture Link -->
    <div
      class="product__img"
      style="
            background-image: url('{{product.image_1.url}}');
          "
    ></div>

    <div class="product__content">
      <!-- * TODO: Product Name -->
      <a
        href="{% url 'main:product' product.id %}"
        style="margin: 0px !important; padding: 0px !important"
      >
        <p
          class="s-l w-h"
          style="height: 7.05vh; align-items: start; overflow: hidden"
        >
          {{product.name}}
        </p>
      </a>
      <!-- * TODO: Product Ratings -->
      <div style="display: flex; margin: 6.25px 0px">
        {% with ratings=product.ratings %}
        <span></span>
        {% include "templates/ratings.html" %}
        <span></span>
        {% endwith %}
      </div>
      <!-- * TODO: Product Price -->
      <p class="s-l w-h">USD {{ product.price }}</p>
      <!-- * TODO: Product Shipping Estimate -->
      <p class="s-m w-l">+USD {{ product.shipping_price }} shipping estimate</p>
      <!-- * TODO: Details Btn -->
      <a
        href="{% url 'dashboard:edit_product' product.id %}"
        class="product__link"
        >View Details</a
      >
    </div>
  </div>

  {% endfor %}
</div>

<script src="{% static 'dashboard/js/my_products.js' %}"></script>
{% endblock viewContent %}

dashboard/templates/dashboard/navbar.html
{% load static %}

<link
  href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp"
  rel="stylesheet"
/>
<link rel="stylesheet" href="{% static 'base/css/base.css' %}" />
<link rel="stylesheet" href="{% static 'dashboard/css/navbar.css' %}" />

<nav class="shadow">
  <div class="nav-bg"></div>
  <ul>
    <a id="nav-home" href="{% url 'dashboard:home' %}">
      <span class="material-icons-outlined"> home </span>
      <p class="s-l w-h">Home</p>
    </a>

    <a id="nav-cart" href="{% url 'dashboard:cart' %}">
      <span class="material-icons-outlined"> shopping_cart </span>
      <p class="s-l w-h">Cart</p>
    </a>

    <a id="nav-watchlist" href="{% url 'dashboard:watchlist' %}">
      <span class="material-icons-outlined"> remove_red_eye </span>
      <p class="s-l w-h">Watchlist</p>
    </a>

    <a id="nav-wishlist" href="{% url 'dashboard:wishlist' %}"
      ><span class="material-icons-outlined"> star_rate </span>
      <p class="s-l w-h">Wishlist</p>
    </a>

    <a id="nav-crm" href="{% url 'dashboard:crm' %}"
      ><span class="material-icons-outlined"> groups </span>
      <p class="s-l w-h">CRM</p>
    </a>

    <a id="nav-my-products" href="{% url 'dashboard:my_products' %}"
      ><span class="material-icons-outlined"> inventory_2 </span>
      <p class="s-l w-h">My Products</p>
    </a>

    <a id="nav-add-product" href="{% url 'dashboard:add_product' %}"
      ><span class="material-icons-outlined"> add_box </span>
      <p class="s-l w-h">Add Product</p>
    </a>

    <a id="nav-revenue" href="{% url 'dashboard:revenue' %}"
      ><span class="material-icons-outlined"> paid </span>
      <p class="s-l w-h">Revenue</p>
    </a>

    <a id="nav-settings" href="{% url 'dashboard:settings' %}">
      <span class="material-icons-outlined"> settings </span>
      <p class="s-l w-h">Settings</p>
    </a>
  </ul>

  <button class="nav__sign-out">
    <span class="material-icons-outlined"> logout </span>

    <a href="{% url 'authentication:sign_out' %}" style="padding: 0; margin: 0">
      <p class="s-m w-h c-white">Sign Out</p>
    </a>
  </button>
</nav>

dashboard/templates/dashboard/revenue.html
{% extends "dashboard/dashboard.html" %} {% load static %}

<hr />
{% block viewContent %}
<link rel="stylesheet" href="{% static 'dashboard/css/revenue.css' %}" />

<div class="revenue">
  <!-- Revenue -->
  <p class="s-xl w-h">Revenue</p>
  <div class="revenue__revenue">
    <div class="revenue__timePeriod bg-darkBlue c-white" data-time="today">
      <!-- Today -->
      <p class="s-l w-h">Today</p>
      <div style="margin-top: 12.5px">
        <p class="s-m w-h">USD {{ todays_revenue|floatformat:2 }}</p>
        <p class="s-s w-l" style="opacity: 0.5">
          / {{todays_sale}} products sold
        </p>
      </div>
    </div>
    <!-- Yesterday -->
    <div class="revenue__timePeriod bg-white" data-time="yesterday">
      <p class="s-l w-h">Yesterday</p>
      <div style="margin-top: 12.5px">
        <p class="s-m w-h">USD {{ yesterdays_revenue|floatformat:2 }}</p>
        <p class="s-s w-l" style="opacity: 0.5">
          / {{yesterdays_sale}} products sold
        </p>
      </div>
    </div>
    <!-- Last Week -->
    <div class="revenue__timePeriod bg-white" data-time="lastweek">
      <p class="s-l w-h">Last Week</p>
      <div style="margin-top: 12.5px">
        <p class="s-m w-h">USD {{ lastweeks_revenue|floatformat:2 }}</p>
        <p class="s-s w-l" style="opacity: 0.5">
          / {{lastweeks_sale}} products sold
        </p>
      </div>
    </div>
    <!-- Last 28 Days -->
    <div class="revenue__timePeriod bg-white" data-time="28days">
      <p class="s-l w-h">Last 28 Days</p>
      <div style="margin-top: 12.5px">
        <p class="s-m w-h">USD {{ last28_revenue|floatformat:2 }}</p>
        <p class="s-s w-l" style="opacity: 0.5">
          / {{last28_sale}} products sold
        </p>
      </div>
    </div>
  </div>

  <!-- Revenue and Sales -->
  <p class="s-xl w-h" style="margin-top: 25px">Sales</p>
  <div class="revenue__revenueSales">
    <!-- Revenue and Sales Info -->
    <div class="revenueSales__info">
      <p class="s-l w-h">Total Revenue</p>
      <p class="s-m w-m">USD {{total_revenue}}</p>
      <p class="s-l w-h" style="margin-top: 25px">Total Sales</p>
      <p class="s-m w-m">{{total_sales}}</p>
    </div>

    <!-- Revenue and Sales Graph -->
    <div class="revenueSales__graph">
      <!-- Keys -->
      <div style="display: flex; align-items: center">
        <p class="s-m w-h" style="margin-right: 6.25px">Revenue</p>
        <div
          class="bg-orange"
          style="width: 10px; height: 10px; border-radius: 2.5px"
        ></div>
        <p class="s-m w-h" style="margin: 0px 6.25px 0px 12.5px">Sales</p>
        <div
          class="bg-darkBlue"
          style="width: 10px; height: 10px; border-radius: 2.5px"
        ></div>
      </div>
      <!-- Graph -->
      <div>
        <canvas id="revenueSales__graph"></canvas>
      </div>
    </div>
  </div>

  <!-- Bestsellers -->
  <p class="s-xl w-h" style="margin-top: 25px">Bestsellers</p>
  <div class="revenue__bestsellers">
    <!-- Bestsellers Table -->
    <table class="bestsellers__table">
      <thead>
        <tr>
          <th class="table__header" style="width: 40%" align="start">
            <p class="s-l w-h">Product</p>
          </th>
          <th class="table__header" style="width: 15%">
            <p class="s-l w-h">Price</p>
          </th>
          <th class="table__header" style="width: 15%">
            <p class="s-l w-h">Sold</p>
          </th>
          <th class="table__header" style="width: 15%">
            <p class="s-l w-h">Revenue</p>
          </th>
        </tr>
      </thead>
      <tbody>
        {% for bestseller in bestsellers %}
        <tr>
          <td class="table__text" style="padding-right: 12.5px">
            <p class="s-m w-m">{{bestseller.name}}</p>
          </td>
          <td class="table__text" align="center">
            <p class="s-m w-m">USD {{ bestseller.price|floatformat:2 }}</p>
          </td>
          <td class="table__text" align="center">
            <p class="s-m w-m">{{bestseller.sold}}</p>
          </td>
          <td class="table__text" align="center">
            <p class="s-m w-m">USD {{ bestseller.revenue|floatformat:2 }}</p>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <!-- Traffic -->
  <p class="s-xl w-h" style="margin-top: 25px">Traffic</p>
  <div class="revenue__traffic">
    <!-- Buttons -->
    <div style="display: flex; margin-bottom: 25px">
      <button class="traffic__btn bg-orange c-white">Views</button>
      <button class="traffic__btn bg-white c-black">Added to Carts</button>
      <button class="traffic__btn bg-white c-black">Added to Watchlist</button>
      <button class="traffic__btn bg-white c-black">Added to Wishlist</button>
    </div>
    <div style="display: flex; align-items: center">
      <!-- Info -->
      <div class="traffic__info">
        <p class="s-l w-h">Product Views</p>
        <p class="s-m w-m">{{ total_views }}</p>
      </div>
      <!-- Graph -->
      <div class="traffic__graph">
        <div style="display: flex; align-items: center">
          <p class="s-m w-h" style="margin-right: 6.25px">Product Views</p>
          <div
            class="bg-orange"
            style="width: 10px; height: 10px; border-radius: 2.5px"
          ></div>
        </div>
        <div>
          <canvas id="traffic__graph"></canvas>
        </div>
      </div>
    </div>
  </div>

  <!-- Product Interactions -->
  <div class="revenue__productInteractions">
    <button class="productInteractions__btn bg-darkBlue c-white">
      <p class="s-l w-h">New Product</p>
      <p class="s-m w-m">Click here to add a new product.</p>
    </button>
    <button class="productInteractions__btn bg-orange c-white">
      <p class="s-l w-h">Update Product</p>
      <p class="s-m w-m">Click here to update existing products.</p>
    </button>
    <button class="productInteractions__btn bg-lightBlue c-white">
      <p class="s-l w-h">Create discount</p>
      <p class="s-m w-m">Click here to add a discount to your products.</p>
    </button>
  </div>

  <!-- Latest Orders -->
  <p class="s-xl w-h" style="margin-top: 25px">Latest Orders</p>
  <div class="revenue__latestOrders">
    <table class="latestOrders__table">
      <thead>
        <tr>
          <th style="width: 40%" class="table__header">
            <p class="s-l w-h">Product</p>
          </th>
          <th style="width: 12%" class="table__header">
            <p class="s-l w-h">Order ID</p>
          </th>
          <th style="width: 12%" class="table__header">
            <p class="s-l w-h">Date</p>
          </th>
          <th style="width: 12%" class="table__header">
            <p class="s-l w-h">Price</p>
          </th>
          <th style="width: 12%" class="table__header">
            <p class="s-l w-h">Status</p>
          </th>
          <th style="width: 12%" class="table__header">
            <p class="s-l w-h"></p>
          </th>
        </tr>
      </thead>

      <tbody>
        {% for order in sorted_latest_orders %}
        <span></span>
        {% for product in order.products.all %}

        <tr>
          <td class="table__text">
            <p class="s-m w-m">{{product.name}}</p>
          </td>
          <td class="table__text">
            <p class="s-m w-m">{{order.id}}</p>
          </td>
          <td class="table__text">
            <p class="s-m w-m">{{ order.time_of_order|date:"d M Y" }}</p>
          </td>
          <td class="table__text">
            <p class="s-m w-m">
              USD {{ product.price|add:product.shipping_price|floatformat:2 }}
            </p>
          </td>
          <td class="table__text">
            <button
              class="table__statusBtn"
              data-status="{{order.status}}"
            ></button>
          </td>
          <td class="table__text">
            <a
              href="{% url 'dashboard:order' order.id %}"
              class="table__detailsBtn bg-darkBlue c-white"
              >Details</a
            >
          </td>
        </tr>

        {% endfor %}
        <span></span>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js@3.3.2/dist/chart.min.js"></script>

{{t_graph_revenue|json_script:"t_graph_revenue"}}
{{t_graph_sales|json_script:"t_graph_sales"}}
{{y_graph_revenue|json_script:"y_graph_revenue"}}
{{y_graph_sales|json_script:"y_graph_sales"}}
{{lw_graph_revenue|json_script:"lw_graph_revenue"}}
{{lw_graph_sales|json_script:"lw_graph_sales"}}
{{te_graph_revenue|json_script:"te_graph_revenue"}}
{{te_graph_sales|json_script:"te_graph_sales"}}
{{lw_graph_views|json_script:"lw_graph_views"}}
{{lw_graph_atc|json_script:"lw_graph_atc"}}
{{lw_graph_atwa|json_script:"lw_graph_atwa"}}
{{lw_graph_atwi|json_script:"lw_graph_atwi"}}

<script type="text/javascript">
  var totalProductViews = "{{total_views}}";
  var totalProductsAddedToCart = "{{total_atc}}";
  var totalProductsAddedToWatchlist = "{{total_atwa}}";
  var totalProductsAddedToWishlist = "{{total_atwi}}";
</script>
<script
  type="text/javascript"
  src="{% static 'dashboard/js/revenue.js' %}"
></script>
{% endblock viewContent %}