aurora/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
    path('', include('information.urls')),
    path('dashboard/', include('dashboard.urls')),

    path("password_reset/", auth_views.PasswordResetView.as_view(),
         name="password_reset"),
    path("password_reset_done/", auth_views.PasswordResetDoneView.as_view(),
         name="password_reset_done"),
    path("password_reset_confirm/<uidb64>/<token>", auth_views.PasswordResetConfirmView.as_view(),
         name="password_reset_confirm"),
    path("password_reset_complete/",
         auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/urls.py
# Imports

from django.urls import path
from . import views

# URL Configurations

app_name = "authentication"
urlpatterns = [
    path("sign_in/", views.sign_in, name="sign_in"),
    path("sign_up/", views.sign_up, name="sign_up"),
    path("sign_out/", views.sign_out, name="sign_out"),

    path("password_reset/", views.password_reset, name="password_reset"),
    path("password_change/<uidb64>/<token>/",
         views.password_change, name="password_change"),

    path("verify_user/<huid>/", views.verify_user, name="verify_user")
]

main/urls.py
# Imports

from django.urls import path
from . import views

# URL Configurations

app_name = "main"
urlpatterns = [
    path("", views.index, name="index"),
    path("products/", views.products, name="products"),
    path("product/<int:id>", views.product, name="product"),
    path("category/<int:id>", views.category, name="category"),
    path("brand/", views.brand, name="brand"),
    path("sub_category/<int:id>", views.sub_category, name="sub_category"),
    path("product_type/<int:id>", views.product_type, name="product_type"),
    path("seller/", views.seller, name="seller"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'base/css/navbar.css' %}" />
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}" />
    <link
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp"
      rel="stylesheet"
    />

    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

    <script
      src="https://kit.fontawesome.com/c1e316d6ea.js"
      crossorigin="anonymous"
    ></script>

    <title>{% block title %} Aurora {% endblock title %}</title>
  </head>

  <body>
    {% include "templates/navbar.html" %} {% block content %}
    <h1>Hello World</h1>
    {% endblock content %}
    <script src="{% static 'base/js/navbar.js' %}"></script>
    <script src="{% static 'base/js/anime.min.js' %}"></script>
    <script src="{% static 'base/js/base.js' %}"></script>
  </body>
</html>

templates/navbar.html
<nav class="nav">
  <a href="{% url 'main:index' %}" class="nav__index"
    ><p class="s-m w-m">Aurora</p></a
  >

  <div class="nav__links">
    <a href="{% url 'main:products' %}" class="link links__link"
      ><p class="s-m w-m">Products</p></a
    >
    <a href="#" class="link links__link" id="categories"
      ><p class="s-m w-m">Categories</p></a
    >
    <a href="#" class="link links__link"><p class="s-m w-m">About</p></a>
    <a href="#" class="link links__link"><p class="s-m w-m">Legal</p></a>
  </div>

  <a href="{% url 'authentication:sign_in' %}" class="link links__link"
    ><p class="s-m w-m">Sign in</p></a
  >

  <div class="dropdown">
    {% for category in all_categories %}
    <a href="{% url 'main:category' category.id %}" class="dropdown__link">
      <div
        class="dropdown__link__img"
        style="background-image: url('{{ category.image.url }}')"
      ></div>
      <p class="s-m w-m">{{ category.name }}</p>
    </a>
    {% endfor %}
  </div>
</nav>

templates/ratings.html
<!-- Rating 1 -->
{% if ratings == 0 %}
<span class="material-icons s-l"> star_border </span>
<span class="material-icons s-l"> star_border </span>
<span class="material-icons s-l"> star_border </span>
<span class="material-icons s-l"> star_border </span>
<span class="material-icons s-l"> star_border </span>
{% elif ratings == 1 %}
<span class="material-icons s-l"> star </span>
<span class="material-icons s-l"> star_border </span>
<span class="material-icons s-l"> star_border </span>
<span class="material-icons s-l"> star_border </span>
<span class="material-icons s-l"> star_border </span>

{% elif ratings == 2 %}
<span class="material-icons s-l"> star </span>
<span class="material-icons s-l"> star </span>
<span class="material-icons s-l"> star_border </span>
<span class="material-icons s-l"> star_border </span>
<span class="material-icons s-l"> star_border </span>

{% elif ratings == 3 %}
<span class="material-icons s-l"> star </span>
<span class="material-icons s-l"> star </span>
<span class="material-icons s-l"> star </span>
<span class="material-icons s-l"> star_border </span>
<span class="material-icons s-l"> star_border </span>

{% elif ratings == 4 %}
<span class="material-icons s-l"> star </span>
<span class="material-icons s-l"> star </span>
<span class="material-icons s-l"> star </span>
<span class="material-icons s-l"> star </span>
<span class="material-icons s-l"> star_border </span>

{% elif ratings == 5 %}
<span class="material-icons s-l"> star </span>
<span class="material-icons s-l"> star </span>
<span class="material-icons s-l"> star </span>
<span class="material-icons s-l"> star </span>
<span class="material-icons s-l"> star </span>
{% endif %}

templates/textInput.html
{% load static %}
<link rel="stylesheet" href="{% static 'base/css/textInput.css' %}" />

<div class="textInput">
  <span class="material-icons-outlined textInput__icon s-xl w-m">
    {{ icon }}
  </span>
  <input
    class="textInput__input s-l w-m"
    type="{{ type }}"
    placeholder="{{ title }}"
    name="{{ name }}"
    value="{{ value }}"
    required="{{ required }}"
  />
</div>

<script src="{% static 'base/js/anime.min.js' %}"></script>
<script src="{% static 'base/js/textInput.js' %}"></script>