aurora/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
    path('', include('information.urls')),
    path('dashboard/', include('dashboard.urls')),

    path("password_reset/", auth_views.PasswordResetView.as_view(),
         name="password_reset"),
    path("password_reset_done/", auth_views.PasswordResetDoneView.as_view(),
         name="password_reset_done"),
    path("password_reset_confirm/<uidb64>/<token>", auth_views.PasswordResetConfirmView.as_view(),
         name="password_reset_confirm"),
    path("password_reset_complete/",
         auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
# Imports

from django.urls import path
from . import views

# URL Configurations

app_name = "main"
urlpatterns = [
    path("", views.index, name="index"),
    path("products/", views.products, name="products"),
    path("product/<int:id>", views.product, name="product"),
    path("category/<int:id>", views.category, name="category"),
    path("brand/", views.brand, name="brand"),
    path("sub_category/<int:id>", views.sub_category, name="sub_category"),
    path("product_type/<int:id>", views.product_type, name="product_type"),
    path("seller/", views.seller, name="seller"),
]

main/views.py
# Imports


from datetime import time
from main.models import *
from dashboard.models import *

from main.webscraper import permission
from main.product_types import *
from main.filters import *

from django.shortcuts import render, redirect, reverse
from django.contrib import messages

from asgiref.sync import sync_to_async

import json


# Views


def cart_btn_handler(request, cart):
    product = Product.objects.get(id=request.POST["cart"])

    if product in cart.products.all():
        cart.products.remove(product)
        messages.add_message(
            request, messages.ERROR, f"{product.name} has been removed from your cart.")
    else:
        cart.products.add(product)
        product_cart = ProductCart.objects.create(product=product)
        product_cart.save()
        messages.add_message(
            request, messages.SUCCESS, f"{product.name} has been added to your cart.")

    cart.save()


def watchlist_btn_handler(request, watchlist):
    product = Product.objects.get(id=request.POST["watchlist"])

    if product in watchlist.products.all():
        watchlist.products.remove(product)
        messages.add_message(
            request, messages.ERROR, f"{product.name} has been removed from your watchlist.")
    else:
        watchlist.products.add(product)
        product_watchlist = ProductsAddedToWatchlist.objects.create(
            product=product)
        product_watchlist.save()
        messages.add_message(
            request, messages.SUCCESS, f"{product.name} has been added to your watchlist.")

    watchlist.save()


def wishlist_btn_handler(request, wishlist):
    product = Product.objects.get(id=request.POST["wishlist"])

    if product in wishlist.products.all():
        wishlist.products.remove(product)
        messages.add_message(
            request, messages.ERROR, f"{product.name} has been removed from your wishlist.")
    else:
        wishlist.products.add(product)
        product_wishlist = ProductsAddedToWishlist.objects.create(
            product=product)
        product_wishlist.save()
        messages.add_message(
            request, messages.SUCCESS, f"{product.name} has been added to your wishlist.")

    wishlist.save()


def index(request):
    all_categories = Category.objects.order_by('name')
    products = Product.objects.all()

    context = {
        "all_categories": all_categories,
        "products": products,
    }

    if request.user.is_authenticated:
        user = request.user
        custom_user = CustomUser.objects.get(user=user)
        cart = Cart.objects.get(user=custom_user)
        wishlist = Wishlist.objects.get(user=custom_user)
        watchlist = Watchlist.objects.get(user=custom_user)

        context["cart"] = cart
        context["wishlist"] = wishlist
        context["watchlist"] = watchlist

    if request.method == "POST":
        if request.user.is_authenticated:
            if "cart" in request.POST:
                cart_btn_handler(request, cart)

            if "wishlist" in request.POST:
                wishlist_btn_handler(request, wishlist)

            if "watchlist" in request.POST:
                watchlist_btn_handler(request, watchlist)

        else:
            return redirect(reverse("authentication:sign_in"))

    return render(request, "main/index.html", context)


def products(request):
    all_categories = Category.objects.order_by('name')
    products = Product.objects.all()

    context = {
        "all_categories": all_categories,
        "products": products,
    }

    if request.user.is_authenticated:
        user = request.user
        custom_user = CustomUser.objects.get(user=user)
        cart = Cart.objects.get(user=custom_user)
        wishlist = Wishlist.objects.get(user=custom_user)
        watchlist = Watchlist.objects.get(user=custom_user)

        context["cart"] = cart
        context["wishlist"] = wishlist
        context["watchlist"] = watchlist

    if request.method == "POST":
        if request.user.is_authenticated:
            if "cart" in request.POST:
                cart_btn_handler(request, cart)

            if "wishlist" in request.POST:
                wishlist_btn_handler(request, wishlist)

            if "watchlist" in request.POST:
                watchlist_btn_handler(request, watchlist)

        else:
            return redirect(reverse("authentication:sign_in"))

    return render(request, "main/products.html", context)


def product(request, id):
    all_categories = Category.objects.order_by('name')

    product = Product.objects.get(id=id)
    product_view = ProductView.objects.create(product=product)
    product_view.save()

    seller_products = Product.objects.filter(seller=product.seller)
    reviews = Review.objects.filter(product=product)

    context = {
        'all_categories': all_categories,
        "product": product,
        "seller_products": seller_products,
        "reviews": reviews,
    }

    if request.user.is_authenticated:
        user = request.user
        custom_user = CustomUser.objects.get(user=user)
        cart = Cart.objects.get(user=custom_user)
        wishlist = Wishlist.objects.get(user=custom_user)
        watchlist = Watchlist.objects.get(user=custom_user)

        context["cart"] = cart
        context["wishlist"] = wishlist
        context["watchlist"] = watchlist

    if request.method == "POST":
        if request.user.is_authenticated:
            if "cart" in request.POST:
                cart_btn_handler(request, cart)

            if "wishlist" in request.POST:
                wishlist_btn_handler(request, wishlist)

            if "watchlist" in request.POST:
                watchlist_btn_handler(request, watchlist)

        else:
            return redirect(reverse("authentication:sign_in"))

    return render(request, "main/product.html", context)


def category(request, id):

    category = Category.objects.get(id=id)
    sub_categories = SubCategory.objects.filter(
        category=category).order_by('name')

    all_categories = Category.objects.order_by('name')

    products = Product.objects.all()

    user = request.user
    custom_user = CustomUser.objects.get(user=user)
    cart = Cart.objects.get(user=custom_user)
    wishlist = Wishlist.objects.get(user=custom_user)
    watchlist = Watchlist.objects.get(user=custom_user)

    context = {
        "category": category,
        "sub_categories": sub_categories,
        'all_categories': all_categories,
        "products": products,
        "cart": cart,
        "wishlist": wishlist,
        "watchlist": watchlist
    }

    if request.method == "POST":
        if "cart" in request.POST:
            cart_btn_handler(request, cart)

        if "wishlist" in request.POST:
            wishlist_btn_handler(request, wishlist)

        if "watchlist" in request.POST:
            watchlist_btn_handler(request, watchlist)

    return render(request, "main/category.html", context)


def brand(request):

    context = {}
    return render(request, "main/brand.html", context)


def sub_category(request, id):

    all_categories = Category.objects.order_by('name')

    sub_category = SubCategory.objects.get(id=id)
    product_types = ProductType.objects.filter(
        sub_category=sub_category, parent_product_type="").order_by('name')

    products = Product.objects.all()

    context = {
        "sub_category": sub_category,
        "product_types": product_types,
        'all_categories': all_categories,
        "products": products,


    }
    return render(request, "main/sub_category.html", context)


def product_type(request, id):

    all_categories = Category.objects.order_by('name')

    filter_categories = []
    filter_categorys_num = 0

    products = Product.objects.all()

    product_type = ProductType.objects.get(id=id)
    children_product_types = ProductType.objects.filter(
        parent_product_type=product_type.name, sub_category=product_type.sub_category)
    filters = Filter.objects.filter(
        product_type=product_type).order_by('filter_category', 'name')

    if len(children_product_types) != 0:
        children_product_types_exists = True
    else:
        children_product_types_exists = False

    for filter in filters:

        if filter.filter_category in filter_categories:
            pass
        else:
            filter_categories.append(filter.filter_category)
            filter_categorys_num += 1

    context = {
        "product_type": product_type,
        "children_product_types": children_product_types,
        "filters": filters,
        "filter_categories": filter_categories,
        "children_product_types_exists": children_product_types_exists,
        'all_categories': all_categories,
        "products": products,
    }
    return render(request, "main/product_type.html", context)


def seller(request):
    context = {}
    return render(request, "main/product_seller.html", context)


# permission()

# add_product_types()

# filters_for_product_type()

main/templates/main/brand.html
{% extends "templates/base.html" %} {% load static %} {% block content %}
<link rel="stylesheet" href="{% static 'main/css/brand.css' %}" />

<div class="main">
  <div class="col1">
    <div class="filter-price">
      <h1 class="filter">Filter by price</h1>
      <input type="range" class="filter-price" min="5" max="10000" step="1" />
      <p class="filter-price"></p>
    </div>

    <div class="filter-seller-ratings">
      <h1 class="filter">Filter by seller ratings</h1>
      <input
        type="range"
        class="filter-seller-ratings"
        min="1"
        max="5"
        step="0.5"
      />
      <p class="filter-seller-ratings"></p>
    </div>

    <div class="filter-condition">
      <h1 class="filter">Filter by Condition</h1>
      <p class="filter-condition">
        <input
          class="filter-condition"
          type="checkbox"
          name="filter-condition"
        />
        Brand New
      </p>
      <p class="filter-condition">
        <input
          class="filter-condition"
          type="checkbox"
          name="filter-condition"
        />
        Used
      </p>
      <p class="filter-condition">
        <input
          class="filter-condition"
          type="checkbox"
          name="filter-condition"
        />
        Not Specified
      </p>
    </div>

    <div class="filter-delivery">
      <h1 class="filter">Filter by Delivery</h1>
      <p class="filter-delivery">
        <input class="filter-delivery" type="checkbox" name="filter-delivery" />
        Free International Shipping
      </p>
      <p class="filter-delivery">
        <input class="filter-delivery" type="checkbox" name="filter-delivery" />
        International Shipping
      </p>
      <p class="filter-delivery">
        <input class="filter-delivery" type="checkbox" name="filter-delivery" />
        Free Shipping
      </p>
    </div>

    <div class="filter-returns">
      <h1 class="filter">Filter by returns</h1>
      <p class="filter-returns">
        <input
          class="filter-returns"
          type="checkbox"
          name="filter-returns"
        />Free returns
      </p>
      <p class="filter-returns">
        <input
          class="filter-returns"
          type="checkbox"
          name="filter-returns"
        />Paid returns
      </p>
      <p class="filter-returns">
        <input class="filter-returns" type="checkbox" name="filter-returns" />No
        returns
      </p>
    </div>

    <div class="filter-seller-account">
      <h1 class="filter">Filter by Seller Account</h1>
      <p class="filter-seller-account">
        <input
          class="filter-seller-account"
          type="checkbox"
          name="filter-seller-account"
        />New seller
      </p>
      <p class="filter-seller-account">
        <input
          class="filter-seller-account"
          type="checkbox"
          name="filter-seller-account"
        />Verired seller
      </p>
      <p class="filter-seller-account">
        <input
          class="filter-seller-account"
          type="checkbox"
          name="filter-seller-account"
        />Top rated seller
      </p>
    </div>
  </div>
  <div class="col2">
    <div class="brand-img">
      <p class="brand">Dell</p>
      <button class="show-search">
        <span class="material-icons search">search</span>
      </button>
      <div class="search-cont">
        <input type="text" class="search" placeholder="Search" />
        <button class="search">
          <span class="material-icons search">search</span>
        </button>
      </div>
      <img src="{% static 'base/img/brands/dell.jpg' %}" alt="" class="vis" />
    </div>
    <div class="prods-cont">
      <a href="{% url 'main:product' %}" class="prod-card">
        <div class="prod-img-cont">
          <img class="blur" src="{% static 'base/img/test_products/test12.png' %}"></img>
          <img class="vis" src="{% static 'base/img/test_products/test12.png' %}"></img>

          <p class="pop-account">Verified Seller</p>
          <button class="account"><span class="material-icons">
            verified
            </span></button>
     
        </div>
        <div class="prod-text-cont">
          <p class="prod-name">[Review Unit] Dell XPS 17 9700 i7-10750GH GTX 1650 Ti 4GB GDDR6</p>

          <p class="pop-price">Price</p>
          <button class="price">USD 1450.00</button>

          <p class="pop-save">Save</p>
          <button class="save"><span class="material-icons">
            favorite_border
            </span></button>
            
          <p class="pop-cart">Add to cart</p>
          <button class="add-to-cart">
            <img src="{% static 'base/img/cart.svg' %}">
          </button>

          <p class="pop-shipping">Shipping</p>
          <button class="shipping">USD 0</button>

        </div>
      </a>
    </div>
  </div>
</div>

<script src="{% static 'main/js/brand.js' %}"></script>

{% endblock content %}

main/templates/main/category.html
{% extends "templates/base.html" %} {% load static %}
<hr />
{% block title %} {{category.name}} {% endblock title %} {% block content %}
<link rel="stylesheet" href="{% static 'main/css/category.css' %}" />

<div class="categories">
  <div class="categories__filters">
    <div class="filters__filter module shadow bg-white">
      <p class="s-m w-h">Price</p>
      <input type="range" min="5" max="10000" step="1" />
    </div>

    <div class="filters__filter module shadow bg-white">
      <p class="s-m w-h">Seller Ratings</p>
      <input type="range" min="0" max="5" step="1" />
    </div>

    <div class="filters__filter module shadow c-white bg-darkBlue">
      <p class="s-m w-h">Condition</p>
      <p class="s-s w-l">
        <input type="checkbox" />
        Brand New
      </p>
      <p class="s-s w-l">
        <input type="checkbox" />
        Used
      </p>
    </div>

    <div class="filters__filter module shadow c-white bg-orange">
      <p class="s-m w-h">Shipping</p>
      <p class="s-s w-l">
        <input type="checkbox" />
        Free
      </p>
      <p class="s-s w-l">
        <input type="checkbox" />
        International
      </p>
    </div>

    <div class="filters__filter module shadow bg-paleBlue">
      <p class="s-m w-h">Returns</p>
      <p class="s-s w-l">
        <input type="checkbox" />
        Paid returns
      </p>
      <p class="s-s w-l">
        <input type="checkbox" />
        Free returns
      </p>
      <p class="s-s w-l">
        <input type="checkbox" />
        No returns
      </p>
    </div>

    <div class="filters__filter module shadow c-white bg-red">
      <p class="s-m w-h">Seller Account</p>
      <p class="s-s w-l">
        <input type="checkbox" />
        New
      </p>
      <p class="s-s w-l">
        <input type="checkbox" />
        Top rated
      </p>
      <p class="s-s w-l">
        <input type="checkbox" />
        Verified
      </p>
    </div>
  </div>

  <div class="categories__content">
    <div class="content__sub-categories">
      {% for sub_category in sub_categories %}
      <a
        class="categories__sub-category"
        href="{% url 'main:sub_category' sub_category.id %}"
      >
        <div
          class="sub-category__img"
          style="background-image: url('{{ sub_category.image.url }}');"
        ></div>
        <p class="s-m w-m c-white" style="position: relative; z-index: 1">
          {{sub_category.name}}
        </p>
      </a>

      {% endfor %}
    </div>

    <div class="categories__search">
      {% with type="text" %}
      <span></span>
      {% with title="Search" %}
      <span></span>
      {% with icon="search" %}
      <span></span>
      {% with name="search" %}
      <span></span>
      {% include "templates/textInput.html" %}
      <span></span>
      {% endwith %}
      <span></span>
      {% endwith %}
      <span></span>
      {% endwith %}
      <span></span>
      {% endwith %}
    </div>

    {% if messages %} {% for message in messages %}
    <p
      class="s-l w-h {{ message.tags }}"
      style="width: calc(100% - 50px); margin: 25px 0px 0px 0px"
    >
      {{ message }}
    </p>
    {% endfor %} {% endif %}

    <div class="categories__products">
      {% for product in products %}

      <div class="product">
        <!-- * TODO: Picture Link -->
        <div
          class="product__img"
          style="
            background-image: url('{{product.image_1.url}}');
          "
        ></div>
        <!-- * TODO: Blurred Background -->

        <div class="product__content">
          <!-- * TODO: Product Name -->
          <a href="{% url 'main:product' product.id %}">
            <p
              class="s-l w-h"
              style="height: 7.05vh; align-items: start; overflow: hidden"
            >
              {{product.name}}
            </p>
          </a>
          <!-- * TODO: Product Ratings -->
          <div style="display: flex; margin: 6.25px 0px">
            {% with ratings=product.ratings %}
            <span></span>
            {% include "templates/ratings.html" %}
            <span></span>
            {% endwith %}
          </div>
          <!-- * TODO: Product Price -->
          <p class="s-l w-h">USD {{ product.price }}</p>
          <!-- * TODO: Product Shipping Estimate -->
          <p class="s-m w-l">
            +USD {{ product.shipping_price }} shipping estimate
          </p>
          <!-- * TODO: Add to cart, watchlist and wishlist buttons -->
          <form method="POST" style="display: flex; margin-top: 6.25px">
            {% csrf_token %} {% if product in cart.products.all %}
            <button class="toggled c-red" type="submit" data-color="#ef233c">
              <input type="submit" name="cart" value="{{ product.id }}" />
              <span class="material-icons-outlined s-l">add_shopping_cart</span>
            </button>
            {% else %}
            <button class="toggle" type="submit" data-color="#ef233c">
              <input type="submit" name="cart" value="{{ product.id }}" />
              <span class="material-icons-outlined s-l">add_shopping_cart</span>
            </button>
            {% endif %} {% if product in wishlist.products.all %}
            <button class="toggled c-dark-blue" data-color="#3d5a80">
              <input type="submit" name="wishlist" value="{{ product.id }}" />
              <span class="material-icons-outlined s-l">star_border</span>
            </button>
            {% else %}
            <button class="toggle" data-color="#3d5a80">
              <input type="submit" name="wishlist" value="{{ product.id }}" />
              <span class="material-icons-outlined s-l">star_border</span>
            </button>
            {% endif %} {% if product in watchlist.products.all %}
            <button class="toggled c-orange" data-color="#ee6c4d">
              <input type="submit" name="watchlist" value="{{ product.id }}" />
              <span class="material-icons-outlined s-l">remove_red_eye</span>
            </button>
            {% else %}
            <button class="toggle" data-color="#ee6c4d">
              <input type="submit" name="watchlist" value="{{ product.id }}" />
              <span class="material-icons-outlined s-l">remove_red_eye</span>
            </button>
            {% endif %}
          </form>

          <!-- * TODO: Account Type -->

          {% if product.seller.account_type == "New Seller" %}

          <div class="product__account-type bg-red c-white">
            <span class="material-icons-outlined s-l">new_releases</span>
            <p class="s-s w-h" style="margin-left: 5px">
              {{ product.seller.account_type }}
            </p>
          </div>

          {% elif product.seller.account_type == "Top Rated Seller" %}

          <div class="product__account-type bg-orange c-white">
            <span class="material-icons-outlined s-l">auto_graph</span>
            <p class="s-s w-h" style="margin-left: 5px">
              {{ product.seller.account_type }}
            </p>
          </div>

          {% elif product.seller.account_type == "Verified Seller" %}

          <div class="product__account-type bg-darkBlue c-white">
            <span class="material-icons-outlined s-l">verified</span>
            <p class="s-s w-h" style="margin-left: 5px">
              {{ product.seller.account_type }}
            </p>
          </div>

          {% endif %}
        </div>
      </div>

      {% endfor %}
    </div>
  </div>
</div>

<script>
  const toggleBtns = document.querySelectorAll("button.toggle");

  toggleBtns.forEach((toggleBtn) => {
    toggleBtn.addEventListener("click", function () {
      toggleBtn.classList.toggle("toggled");

      if (toggleBtn.classList.contains("toggled")) {
        toggleBtn.style.color = toggleBtn.getAttribute("data-color");
      } else {
        toggleBtn.style.color = "black";
      }
    });
  });
</script>
<script src="{% static 'main/js/category.js' %}"></script>

{% endblock content %}

main/templates/main/index.html
{% extends "templates/base.html" %} {% load static %} {% block content %}
<link
  href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp"
  rel="stylesheet"
/>
<link rel="stylesheet" href="{% static 'main/css/index.css' %}" />

<div class="main">
  <div
    class="main__banner"
    style="
      background-image: url('https://cdni.iconscout.com/illustration/premium/thumb/family-shopping-2681394-2239883.png');
    "
  ></div>

  <div class="main__search">
    {% with type="text" %}
    <span></span>
    {% with title="Search" %}
    <span></span>
    {% with icon="search" %}
    <span></span>
    {% with name="search" %}
    <span></span>
    {% include "templates/textInput.html" %}
    <span></span>
    {% endwith %}
    <span></span>
    {% endwith %}
    <span></span>
    {% endwith %}
    <span></span>
    {% endwith %}
  </div>

  {% if messages %} {% for message in messages %}
  <p class="s-l w-h {{ message.tags }}" style="margin: 25px 0px 0px 0px">
    {{ message }}
  </p>
  {% endfor %} {% endif %}

  <div class="main__categories">
    {% for category in all_categories %}
    <a
      class="categories__category"
      href="{% url 'main:category' category.id %}"
      style="background-image: url('{{ category.image.url }}');"
    >
      <p class="category__text">{{category.name}}</p>
    </a>

    {% endfor %}
  </div>

  <div class="main__products">
    {% for product in products %}

    <div class="product">
      <!-- * TODO: Picture Link -->
      <div
        class="product__img"
        style="
          background-image: url('{{product.image_1.url}}');
        "
      ></div>
      <!-- * TODO: Blurred Background -->

      <div class="product__content">
        <!-- * TODO: Product Name -->
        <a href="{% url 'main:product' product.id %}">
          <p
            class="s-l w-h"
            style="height: 7.05vh; align-items: start; overflow: hidden"
          >
            {{product.name}}
          </p>
        </a>
        <!-- * TODO: Product Ratings -->
        <div style="display: flex; margin: 6.25px 0px">
          {% with ratings=product.ratings %}
          <span></span>
          {% include "templates/ratings.html" %}
          <span></span>
          {% endwith %}
        </div>
        <!-- * TODO: Product Price -->
        <p class="s-l w-h">USD {{ product.price }}</p>
        <!-- * TODO: Product Shipping Estimate -->
        <p class="s-m w-l">
          +USD {{ product.shipping_price }} shipping estimate
        </p>
        <!-- * TODO: Add to cart, watchlist and wishlist buttons -->
        <form method="POST" style="display: flex; margin-top: 6.25px">
          {% csrf_token %} {% if product in cart.products.all %}
          <button class="toggled c-red" type="submit" data-color="#ef233c">
            <input type="submit" name="cart" value="{{ product.id }}" />
            <span class="material-icons-outlined s-l">add_shopping_cart</span>
          </button>
          {% else %}
          <button class="toggle" type="submit" data-color="#ef233c">
            <input type="submit" name="cart" value="{{ product.id }}" />
            <span class="material-icons-outlined s-l">add_shopping_cart</span>
          </button>
          {% endif %} {% if product in wishlist.products.all %}
          <button class="toggled c-dark-blue" data-color="#3d5a80">
            <input type="submit" name="wishlist" value="{{ product.id }}" />
            <span class="material-icons-outlined s-l">star_border</span>
          </button>
          {% else %}
          <button class="toggle" data-color="#3d5a80">
            <input type="submit" name="wishlist" value="{{ product.id }}" />
            <span class="material-icons-outlined s-l">star_border</span>
          </button>
          {% endif %} {% if product in watchlist.products.all %}
          <button class="toggled c-orange" data-color="#ee6c4d">
            <input type="submit" name="watchlist" value="{{ product.id }}" />
            <span class="material-icons-outlined s-l">remove_red_eye</span>
          </button>
          {% else %}
          <button class="toggle" data-color="#ee6c4d">
            <input type="submit" name="watchlist" value="{{ product.id }}" />
            <span class="material-icons-outlined s-l">remove_red_eye</span>
          </button>
          {% endif %}
        </form>
        <!-- * TODO: Account Type -->

        {% if product.seller.account_type == "New Seller" %}

        <div class="product__account-type bg-red c-white">
          <span class="material-icons-outlined s-l">new_releases</span>
          <p class="s-s w-h" style="margin-left: 5px">
            {{ product.seller.account_type }}
          </p>
        </div>

        {% elif product.seller.account_type == "Top Rated Seller" %}

        <div class="product__account-type bg-orange c-white">
          <span class="material-icons-outlined s-l">auto_graph</span>
          <p class="s-s w-h" style="margin-left: 5px">
            {{ product.seller.account_type }}
          </p>
        </div>

        {% elif product.seller.account_type == "Verified Seller" %}

        <div class="product__account-type bg-darkBlue c-white">
          <span class="material-icons-outlined s-l">verified</span>
          <p class="s-s w-h" style="margin-left: 5px">
            {{ product.seller.account_type }}
          </p>
        </div>

        {% endif %}
      </div>
    </div>

    {% endfor %}
  </div>

  <div class="footer"></div>
</div>

<script type="text/javascript" src="{% static 'main/js/index.js' %}"></script>
<script type="text/javascript" src="{% static 'base/js/base.js' %}"></script>

{% endblock content %}